### ISSUE TITLE
Non space option

### ISSUE THREAD

**Issue by okuryu** [yahoo/intl-relativeformat#31]
If it returns "3 day ago" in English, it returns "3 日前" in Japanese. There are times when the space between "3" and "日前" is not required in Japanese.

This is an use case in Japanese (Chinese maybe has similar situation), so I wish any options for this use case.

FYI, moment.js seems to has customizable relative time format.
http://momentjs.com/docs/#/i18n/changing-locale/

Thought?

**Comment by ericf** [comment]
We're getting this from the Unicode CLDR data. IIRC, they _added_ a space in a recent version to some locales. Would it make sense to file a bug there?

This is what we're getting from CLDR's JSON data:

```json
"relativeTime-type-past": {
    "relativeTimePattern-count-other": "{0} 日前"
}
```

**Comment by caridy** [comment]
yeah, let's close this one. @okuryu let us know if you need help to file the bug on CLDR's JSON data.

**Comment by okuryu** [comment]
Okay, I'll try to file a bug. :+1:

**Comment by caridy** [comment]
@okuryu, you can file it here: http://unicode.org/cldr/trac/newticket

**Comment by okuryu** [comment]
@caridy Done! http://unicode.org/cldr/trac/ticket/8621
