### ISSUE TITLE
How do I load locale data when using Webpack

### ISSUE THREAD

**Issue by Mingan** [yahoo/intl-relativeformat#34]
Hi, I'm trying to figure out how to load locale data in an application using Webpack. The application is based on [Este.js](https://github.com/este/este).

The documentation says that all locales are automatically loaded in Node.js (which I can see when the dev server starts). The other way described is a normal `script` tag for the browser. However, my application is compiled into a single JS file by Webpack and I just can't figure out where and how do I include a specific locale data.

**Comment by caridy** [comment]
We put in place a provision for webpack/browserify to avoid bundling all locales, that config is here: https://github.com/yahoo/intl-relativeformat/blob/master/package.json#L26-L29

What you have to do is simply `require('intl-relativeformat/dist/locale-data/fr.js')` which will include all french locales.

I will update the README to reflect that.

**Comment by caridy** [comment]
docs updated: https://github.com/yahoo/intl-relativeformat/commit/7733d8ba8d7104f5b4ee35bc928c443ee9ecb326

**Comment by Mingan** [comment]
Thank you for such a fast reply and the updated docs. However, I'm still not able to set it up. I'm not sure whether to look for the problem in Babel, Webpack or somewhere else.

I have:

    import IntlRelativeFormat from 'intl-relativeformat';
    require('intl-relativeformat/dist/locale-data/cs.js');

and get `ReferenceError: IntlRelativeFormat is not defined` in the locale file. Babel creates unusable names, so I tried importing IntlRelativeFormat under a different name and then assigning it to a `IntlRelativeFormat` variable, the context is however still different. I tried googling but couldn't find anything about how to include a non-module JS file and run it in the current context.

**Comment by caridy** [comment]
```
import IntlRelativeFormat from 'intl-relativeformat';
import 'intl-relativeformat/dist/locale-data/cs.js';
```

should be enough since `intl-relativeformat` does some magic to register a global variable that will be used by the locale-date to access the internal registry of the library, and I'm pretty sure babel will not mess with that part of the code. Can you create a very tiny repro case so we can debug this?

/cc @sebmck

**Comment by Mingan** [comment]
import IntlRelativeFormat from 'intl-relativeformat';
    import 'intl-relativeformat/dist/locale-data/cs.js';

unfortunately doesn't do the trick. I'll try to create a debug repo over the weekend and get back to you.

**Comment by sebmck** [comment]
It's not a Babel issue, running:

```javascript
require('intl-relativeformat');
require('intl-relativeformat/dist/locale-data/cs.js');
```

produces the same error.

**Comment by chicoxyzzy** [comment]
This issue is still exists and this is not a Babel issue. Also Webpack's imports-loader doesn't help

**Comment by gajus** [comment]
@Mingan can this be re-opened?

What @kittens said, – this is not a Babel issue.

> should be enough since intl-relativeformat does some magic to register a global variable that will  [..]

There needs to be no magic. `require('intl-relativeformat/dist/locale-data/*.js')` (or equivalent), should simply return an object that we could use then to populate `IntlRelativeFormat`, e.g.

```js
import IntlRelativeFormat from 'intl-relativeformat';
import IntlRelativeFormatLocaleDataEn from 'intl-relativeformat/dist/locale-data/en';

new IntlRelativeFormat('en', IntlRelativeFormatLocaleDataEn);
```

**Comment by Mingan** [comment]
@gajus re-opening is not up to me. 

Personally, I don't have any interest in this issue any more; my affected project is no longer alive.

**Comment by gajus** [comment]
Sorry, wrongly assumed you are one of the maintainers.

@caridy Please re-open the issue.

**Comment by gajus** [comment]
Interim, this can be fixed using webpack:

```bash
npm install imports-loader --save-dev
npm install exports-loader --save-dev
```

```js
if (typeof process === 'undefined' || !process.release || process.release.name !== 'node') {
  const IntlRelativeFormatLocaleDataEn = require('exports?localeData!imports?IntlRelativeFormat=>{__addLocaleData: (data) => {localeData.push(data);}}!imports?localeData=>[]!intl-relativeformat/dist/locale-data/en.js');

  IntlRelativeFormatLocaleDataEn.map((data) => {
    IntlRelativeFormat.__addLocaleData(data);
  });
}
```

**Comment by MoOx** [comment]
Until this lib handle this the proper way, you can (warning it's gross) do `window.IntlRelativeFormat = IntlRelativeFormat` between the first require and require that handle the locales.
