### ISSUE TITLE
Not able to load IntlRelativeFormat with only a couple locales with module bundler

### ISSUE THREAD

**Issue by mikaelcastellani** [yahoo/intl-relativeformat#35]
Hi, I would like to bundle my code using a module bundler but with only a few locales loaded instead of the all 200+. You currently recommend to use the script tag to import a specific locale but it is not compatible with the module bundler way of doing.
For the moment I am running require('intl-relativeformat/lib/locales.js') that works fine except that we cannot restrain the number of locales.

Would you have any recommendations ? Loading the locale-data files does not work because the module bundler executes the code within a specific context where IntlRelativeFormat is in.

Thank you

**Comment by caridy** [comment]
Browserify/Webpack integration info is here:
https://github.com/yahoo/intl-relativeformat#bundling-intlrelativeformat-with-browserifywebpack

**Comment by micaste** [comment]
Thanks. Those lines of code did not work for me because my code is written inside a module loaded by Browserify, and writing var IntlRelativeFormat will not declare that variable as a global variable.
And anyway, we are developing a library and therefore do not want to pollute the code that will embed ours with a global variable.
The solution we found is this one, because Browserify allows to share a context between all the modules it imports, taking in account the order : 
 ```javascript
var exportedVariable = require('intl-relativeformat');
global.IntlMessageFormat = exportedVariable;
require('intl-messageformat/dist/locale-data/en.js');
require('intl-messageformat/dist/locale-data/fr.js');

delete global.IntlMessageFormat;

module.export = exportedVariable;
```

**Comment by caridy** [comment]
ah, that makes sense. thanks for sharing the solution.

**Comment by chicoxyzzy** [comment]
well... will this issue be fixed?

**Comment by chicoxyzzy** [comment]
I can send PR. Something that will work like so

```javascript
var IntlRelativeFormat = require('intl-relativeformat');
require('intl-relativeformat/dist/locale-data/en.js')(IntlRelativeFormat);
require('intl-relativeformat/dist/locale-data/fr.js')(IntlRelativeFormat);
```

**Comment by chicoxyzzy** [comment]
IMO this issue shouldn't be closed

**Comment by xomyaq** [comment]
Hey, guys, I think this should be documented or preferably fixed

**Comment by jbe456** [comment]
Couldn't we modify the require of locales to export a function that takes the `IntlMessageFormat` variable?

```
const IntlMessageFormat = require('intl-messageformat');
require('intl-messageformat/dist/locale-data/en.js')(IntlMessageFormat);
require('intl-messageformat/dist/locale-data/fr.js')(IntlMessageFormat);
```
