### ISSUE TITLE
Question around registering non-default locales

### ISSUE THREAD

**Issue by Ianfeather** [yahoo/intl-relativeformat#36]
Hi there, just a question I'm hoping you can help me with in order to understand the code. I currently have an issue that french translations are only working server side and not client side. 

I am loading all the locale data on the client and (via react-intl) this is working correctly for all other types of intl (number, message etc.) It falls down with relative and I've been trying to work my way through the code to understand where the problem is and what I might be doing incorrectly.

Here I see you're adding all localeData on the server hence why it works fine https://github.com/yahoo/intl-relativeformat/blob/master/index.js#L9

This is skipped on the client and `addLocaleData` is only called with the defaultLocale which you export from `'en'` https://github.com/yahoo/intl-relativeformat/blob/master/src/main.js#L6. If I check `RelativeFormat.__localeData__` I see that `en` is the only one registered.

And then, in '`react-intl'`, the mixin exports `getRelativeFormat: intl$format$cache$$["default"](intl$relativeformat$$["default"])`. Where default is already specified as `en`. 

My question is at what point does the localeData that is registered on the `window.Intl` instance get copied over to the `IntlRelativeFormat` module? I feel like this is the part I need to troubleshoot to see where I'm going wrong and to understand it. 

Thanks in advance for any help you can give me.

**Comment by ericf** [comment]
If this is still a problem with React Intl v2.0.0-beta-2+, could you open it on that repo.
