### ISSUE TITLE
Missing source map files in "lib" folder

### ISSUE THREAD

**Issue by swernerx** [yahoo/intl-relativeformat#43]
The current version in npm does not contains source map files inside the lib folder. Unfortunately these are referenced in the js-files in this folder. This currently breaks building the library with jspm.

**Comment by klimashkin** [comment]
The same issui.
In lib/main.js this string
`//# sourceMappingURL=main.js.map`
So that string goes to my bundle (which I can't uglify because of es6 stuff) and browser tries to find that `main.js.map` on my server.
I think this string should be omitted, don't know why it's there

**Comment by klimashkin** [comment]
I mean this source maps must be in dev mode when developer develops `intl-relativeformat`, if such string exists in /lib files, I can't cut it off with webpack.

**Comment by gustavnikolaj** [comment]
I ran into the same thing right now.

I have a build system that will combine existing source maps into a single one for each of the existing bundles. I cannot get it to work without writing a custom loader that will strip source map references from these modules.

Any chance we can have this fixed?

**Comment by okuryu** [comment]
The latest version have source map files. Please file an issue if you still have any problems.

```
$ npm install intl-messageformat
$ find node_modules/intl-messageformat/lib
node_modules/intl-messageformat/lib
node_modules/intl-messageformat/lib/compiler.js
node_modules/intl-messageformat/lib/compiler.js.map
node_modules/intl-messageformat/lib/core.js
node_modules/intl-messageformat/lib/core.js.map
node_modules/intl-messageformat/lib/en.js
node_modules/intl-messageformat/lib/en.js.map
node_modules/intl-messageformat/lib/es5.js
node_modules/intl-messageformat/lib/es5.js.map
node_modules/intl-messageformat/lib/locales.js
node_modules/intl-messageformat/lib/main.js
node_modules/intl-messageformat/lib/main.js.map
node_modules/intl-messageformat/lib/utils.js
node_modules/intl-messageformat/lib/utils.js.map
```
