### ISSUE TITLE
Narrow/short versions

### ISSUE THREAD

**Issue by santiagoaguiar** [yahoo/intl-relativeformat#46]
Hi!

Is is possible to use the narrow/short versions for relative times? E.g. `{0} wk. ago` instead of `{0} week ago`? They seem to be available on CLDR. 

I would love short version to be `{0}w ago`, but you can't have it all I guess ;).

**Comment by gajus** [comment]
You can just overwrite the instance locales.

https://github.com/yahoo/intl-relativeformat#intlrelativeformat-constructor

**Comment by santiagoaguiar** [comment]
Not sure how that helps, I think we would need an additional option for `IntlRelativeFormat` but I might be missing something.

Here's a related issue for react-intl https://github.com/yahoo/react-intl/issues/393.

**Comment by gajus** [comment]
@santiagoaguiar https://github.com/yahoo/intl-relativeformat/issues/34#issuecomment-245256031 see as an example.

**Comment by santiagoaguiar** [comment]
Ok! Thanks, I was hoping to avoid having to create my own set of localization data for this case. I'll see if I can come around and implement the suggestions of @ericf on yahoo/react-intl#393 by getting the data from the CLDR.

**Comment by dtm5011** [comment]
FYI, support for short relative formats was added in [v2.1.0](https://github.com/yahoo/intl-relativeformat/releases/tag/v2.1.0)

**Comment by santiagoaguiar** [comment]
This looks exactly as what I was asking :) thanks @dtm5011! I'll close the issue.
